config/routes.rb
Rails.application.routes.draw do
  resources :categories, :links
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :links
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
    @links = @category.links
  end

  private

  # def set_category
  #   @category = Category.find(params[:id])
  # end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

# no index method needed

  def new
    @link = Link.new
    @categories = Category.all
  end

  def create
    @link = Link.new(link_params)
    @link.save
    redirect_to categories_path
  end

  private

  def link_params
    params.require(:link).permit(:name, :url, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/categories/index.html.erb
<div class="container">

  <div class="header">
    <div class="header_item" style="margin-left: 2%">
      <%= link_to "Add a Category", new_category_path %>
    </div>
    <div class="header_item">
      <h1>Eve Resources Tool</h1>
    </div>
    <div class="header_item" style="margin-right: 2%">
      <%= link_to "Add a New Link", new_link_path %>
    </div>
  </div>

  <div class="content_div">
    <div class="content">
      <ul>
        <% @categories.each do |category| %>
        <li>
          <%= link_to "#{category.name}", category_path(category.id) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <br>


  <br>
  <br>


</div>

app/views/categories/new.html.erb
<%= link_to image_tag("star.svg", width: 50), categories_path %>
<h1>Add New Category</h1>

<%= form_for @category do |x| %>
  <%= x.text_field(:name) %>
  <%= x.label(:name) %>
  <%= x.submit("Submit") %>
<% end  %>

<h3>Existing Categories</h3>

<ul>
  <% @categories.each do |category| %>
    <li><%= category.name %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<%= link_to image_tag("star.svg", width: 50), categories_path %>

<h1><%= @category.name %></h1>

<ul>
  <% @links.each do |link| %>
    <li>
      <a href="https://evepraisal.com/" target="_blank"><%= link.name.capitalize %></a>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveLinks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<h1>Links</h1>

<ul>
  <% @links.each do |link| %>
    <li>
      <a href="<%= link.url %>"><%= link.name %></a>
    </li>
  <% end %>
</ul>

app/views/links/new.html.erb
<!-- Here I would want to have buttons/radio buttons with existing category names to click when creating a new link
entry that would pass that category_id with the other params to create new instance.
Would also want to have a button that says 'click here to add new category if your desired one is not available
and that would link_to categories#new' -->

<%= link_to image_tag("star.svg", width: 50), categories_path %>

<h1>Add New Resource</h1>

<%= form_for @link do |x| %>
  <%= x.text_field(:name) %>
  <%= x.label(:name) %>
  <%= x.text_field(:url) %>
  <%= x.label(:url) %>
  <ul>
    <% @categories.each do |category| %>
      <li>
        <!-- radio_button(object_name, method, tag_value, options={}) -->
        <%= x.radio_button :category_id, category.id %>
        <%= x.label :category_id, "#{category.name}" %>
      </li>
    <% end %>
  </ul>
  <%= x.submit("Submit") %>
<% end %>

<br>
<br>

<p>Don't see the category you're looking for? Click <%= link_to "here", new_category_path %> to add it to the list </p>